// dashboard/src/pages/register.tsx
"use client"

import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useAuth } from "@/contexts/auth" 
import { zodResolver } from "@hookform/resolvers/zod"
import { useForm } from "react-hook-form"
import { z } from "zod"

import { Button } from "@/components/ui/button"
import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from "@/components/ui/form"
import { Input } from "@/components/ui/input"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Alert, AlertDescription } from "@/components/ui/alert"

const formSchema = z.object({
  email: z.string().email({
    message: "Please enter a valid email address.",
  }),
  username: z.string().min(2, {
    message: "Username must be at least 2 characters.",
  }),
  password: z.string().min(6, {
    message: "Password must be at least 6 characters.",
  }),
  confirmPassword: z.string()
}).refine((data) => data.password === data.confirmPassword, {
  message: "Passwords do not match",
  path: ["confirmPassword"],
})

type FormData = z.infer<typeof formSchema>

export default function Register() {
    const navigate = useNavigate();
    const { register } = useAuth();
    const [error, setError] = useState<string | null>(null);
    const [isLoading, setIsLoading] = useState(false);

    const form = useForm<FormData>({
        resolver: zodResolver(formSchema),
        defaultValues: {
            email: "",
            username: "",
            password: "",
            confirmPassword: "",
        },
    });

    const onSubmit = async (data: FormData) => {
        setError(null);
        setIsLoading(true);

        try {
            const response = await register(data.email, data.username, data.password);
            if (response.success) {
                navigate('/');
            } else {
                setError(response.error || "Registration failed");
            }
        } catch (err) {
            setError("An unexpected error occurred");
        } finally {
            setIsLoading(false);
        }
    };

    return (
        <div className="min-h-screen flex items-center justify-center bg-gray-50 py-12 px-4 sm:px-6 lg:px-8">
            <Card className="w-full max-w-md">
                <CardHeader>
                    <CardTitle>Create your account</CardTitle>
                    <CardDescription>
                        Enter your information to create a new account
                    </CardDescription>
                </CardHeader>
                <CardContent>
                    <Form {...form}>
                        <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-6">
                            <FormField
                                control={form.control}
                                name="email"
                                render={({ field }) => (
                                    <FormItem>
                                        <FormLabel>Email</FormLabel>
                                        <FormControl>
                                            <Input placeholder="you@example.com" type="email" {...field} />
                                        </FormControl>
                                        <FormMessage />
                                    </FormItem>
                                )}
                            />

                            <FormField
                                control={form.control}
                                name="username"
                                render={({ field }) => (
                                    <FormItem>
                                        <FormLabel>Username</FormLabel>
                                        <FormControl>
                                            <Input placeholder="johndoe" {...field} />
                                        </FormControl>
                                        <FormMessage />
                                    </FormItem>
                                )}
                            />

                            <FormField
                                control={form.control}
                                name="password"
                                render={({ field }) => (
                                    <FormItem>
                                        <FormLabel>Password</FormLabel>
                                        <FormControl>
                                            <Input type="password" {...field} />
                                        </FormControl>
                                        <FormMessage />
                                    </FormItem>
                                )}
                            />

                            <FormField
                                control={form.control}
                                name="confirmPassword"
                                render={({ field }) => (
                                    <FormItem>
                                        <FormLabel>Confirm Password</FormLabel>
                                        <FormControl>
                                            <Input type="password" {...field} />
                                        </FormControl>
                                        <FormMessage />
                                    </FormItem>
                                )}
                            />

                            {error && (
                                <Alert variant="destructive">
                                    <AlertDescription>{error}</AlertDescription>
                                </Alert>
                            )}

                            <Button type="submit" className="w-full" disabled={isLoading}>
                                {isLoading ? "Registering..." : "Register"}
                            </Button>

                            <div className="text-sm text-center">
                                <a href="/login" className="text-primary hover:underline">
                                    Already have an account? Login
                                </a>
                            </div>
                        </form>
                    </Form>
                </CardContent>
            </Card>
        </div>
    );
}

// frontend/admin/src/routes/register/+page.svelte
<script lang="ts">
    import { goto } from "$app/navigation";
    import { Button } from "$lib/components/ui/button/index";
    import * as Card from "$lib/components/ui/card/index";
    import * as Alert from "$lib/components/ui/alert/index";
    import { Input } from "$lib/components/ui/input/index";
    import { Label } from "$lib/components/ui/label/index";
    import { authHelpers } from "$lib/stores/auth";
    
    let email = $state<string>("");
    let username = $state<string>("");
    let password = $state<string>("");
    let confirmPassword = $state<string>("");
    let registerLoading = $state<boolean>(false);
    let registerError = $state<string>("");

    async function handleRegister(event:SubmitEvent): Promise<void> {
        event.preventDefault();
        registerLoading = true;
        registerError = '';

        if (!email.includes('@')) {
            registerError = 'Please enter a valid email address';
            registerLoading = false;
            return;
        }

        if (password.length < 6) {
            registerError = 'Password must be at least 6 characters';
            registerLoading = false;
            return;
        }

        if (password !== confirmPassword) {
            registerError = 'Passwords do not match';
            registerLoading = false;
            return;
        }

        try {
            const result:any = await authHelpers.register(email, username, password);
            if (result.success) {
                goto("/");
            } else {
                registerError = result.error;
            }
        } catch (error) {
            registerError = "Error occurred while logging in";
        } finally {
            registerLoading= false;
        }
    }
</script>

<div class="flex justify-center items-center min-h-screen bg-gray-100">
    <Card.Root class="w-full max-w-md shadow-lg">
        <Card.Header class="space-y-1">
            <Card.Title class="text-2xl text-center">Login</Card.Title>
            <Card.Description class="text-center text-gray-500">
                Input details to create your account
            </Card.Description>
        </Card.Header>
        <Card.Content>
            <form onsubmit={handleRegister} class="space-y-4">
                <div class="space-y-2">
                    <Label for="email" class="text-sm font-medium">Email</Label>
                    <Input 
                        id="email"
                        type="email" 
                        bind:value={email} 
                        placeholder=""
                        required
                        class="w-full"
                    />
                </div>
                <div class="space-y-2">
                    <Label for="username" class="text-sm font-medium">Username</Label>
                    <Input 
                        id="username"
                        type="text" 
                        bind:value={username} 
                        placeholder=""
                        required
                        class="w-full"
                    />
                </div>
                <div class="space-y-2">
                    <Label for="password" class="text-sm font-medium">Password</Label>
                    <Input 
                        id="password"
                        type="password" 
                        bind:value={password} 
                        placeholder=""
                        required
                        class="w-full"
                    />
                </div>
                <div class="space-y-2">
                    <Label for="confirmPassword" class="text-sm font-medium">Confirm Password</Label>
                    <Input 
                        id="confirmPassword"
                        type="password" 
                        bind:value={confirmPassword} 
                        placeholder=""
                        required
                        class="w-full"
                    />
                </div>
                {#if registerError}
                    <Alert.Root variant="destructive" class="my-4">
                        <Alert.Title>Authentication Error</Alert.Title> 
                        <Alert.Description>{registerError}</Alert.Description>
                    </Alert.Root>
                {/if}
                <Button 
                    type="submit" 
                    class="w-full" 
                    variant="default"
                    disabled={registerLoading}
                >
                    {registerLoading ? 'Registering...' : 'Register'}
                </Button>
            </form>
        </Card.Content>
        <Card.Footer class="flex justify-center">
            <p class="text-sm text-gray-500">
                Already have an account? <a href="/login" class="text-blue-600 hover:underline">Login</a>
            </p>
        </Card.Footer>
    </Card.Root>
</div>
